sudo: required
services: docker
language: bash
dist: xenial
env:
    global:
      - QEMU_VER=v2.9.1
      - DOCKER_REPO=innovate/docs
    matrix:
      - ARCH=amd64  QEMU_ARCH=x86_64
      - ARCH=armhf  QEMU_ARCH=arm    
      - ARCH=arm64  QEMU_ARCH=aarch64

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - sudo bash -c 'echo "188.166.132.50 docs-controller.innovatete.ch">>/etc/hosts' 

script:
  - docker build -t $DOCKER_REPO:$ARCH-latest --build-arg ARCH=${ARCH} ./

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker push $DOCKER_REPO:$ARCH-latest ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then docker tag $DOCKER_REPO:$ARCH-latest $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT; docker push $DOCKER_REPO:$ARCH-$TRAVIS_COMMIT ; fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$ARCH" == "amd64" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then curl -X PUT -H "Authorization: Bearer $HELMET_KEY" https://docs-controller.innovatete.ch/deployment/$TRAVIS_COMMIT; fi
