name: Docker Image CI

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - amd64
          - armhf
          - arm64
    steps:
    - uses: actions/checkout@v1
    - name: Install qemu
      run: docker run --rm --privileged multiarch/qemu-user-static:register
    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg ARCH=${ARCH} --tag innovate/docs:$ARCH-latest
      env:
        ARCH: ${{ matrix.arch }}
    - name: Docker login
      if: github.event_name == 'push' && github.ref== 'refs/heads/master'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
    - name: Docker push master
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        docker tag innovate/docs:$ARCH:latest innovate/docs:$ARCH-$GITHUB_SHA
        docker push innovate/docs:$ARCH-latest
        docker push innovate/docs:$ARCH-$GITHUB_SHA
      env:
        ARCH: ${{ matrix.arch }}
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Call Helmet
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      run: |
        curl -k -X PUT -H "Authorization: Bearer $HELMET_KEY" https://docs-controller.innovatete.ch/deployment/$GITHUB_SHA
      env:
        HELMET_KEY: ${{ secrets.HELMET_KEY }}
